import '@/public/static/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};  

export default function RootLayout({ children }) {
  let app_url = process.env.NEXT_PUBLIC_APP_URL;

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <title>Miziom - the Future of Payment</title>
        <meta name="description" content="Simple landing page" />
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />


   {/* Tawk.to Script */}
   <script
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/66f82f394cbc4814f7e064b6/1i8snguqm';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />


      </head>
      <body className="leading-normal tracking-normal text-white gradient">
        <nav id="header" className="fixed w-full z-30 top-0 bg-white">
          <div className="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
            <div className="pl-4 flex items-center">
              <a
                className="toggleColour text-white no-underline hover:no-underline font-bold text-2xl lg:text-4xl"
                href={app_url}
              >
                <img src="/images/logo.png" alt="brand logo" width="150" />
              </a>
            </div>
            <div className="block lg:hidden pr-4">
              <button
                id="nav-toggle"
                className="flex items-center p-1 text-pink-800 hover:text-gray-900 focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out"
              >
                <svg
                  className="fill-current h-6 w-6"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>Menu</title>
                  <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
                </svg>
              </button>
            </div>
          </div>
          <hr className="border-b border-gray-100 opacity-25 my-0 py-0" />
        </nav>

        {children}

        <footer className="bg-[#11163f] mt-8">
          <div className="container mx-auto px-8">
            <div className="w-full flex flex-col md:flex-row py-6">
              {/* Footer content */}
              <div className="flex-1 mb-6 text-black">
                <a
                  className="text-pink-600 no-underline hover:no-underline font-bold text-2xl lg:text-4xl"
                  href={app_url}
                >
                  <img src="/images/logo.png" alt="brand logo" width="100" />
                </a>
              </div>
              <div className="flex-1">
                <ul className="list-reset mb-6">
                  <li className="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a
                      href="#"
                      className="no-underline hover:underline text-gray-100 hover:text-pink-500"
                    >
                      FAQ
                    </a>
                  </li>
                  <li className="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a
                      href="#"
                      className="no-underline hover:underline text-gray-100 hover:text-pink-500"
                    >
                      Help
                    </a>
                  </li>
                </ul>
              </div>
              <div className="flex-1">
                <ul className="list-reset mb-6">
                  <li className="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a
                      href={`${app_url}/page/privacy-policy`}
                      className="no-underline hover:underline text-gray-100 hover:text-pink-500"
                    >
                      Privacy policy
                    </a>
                  </li>
                  <li className="mt-2 inline-block mr-2 md:block md:mr-0">
                    <a
                      href={`${app_url}/page/terms-and-conditions`}
                      className="no-underline hover:underline text-gray-100 hover:text-pink-500"
                    >
                      Terms and conditions
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </footer>

     
      </body>
    </html>
  );
}
